openapi: 3.0.1
info:
  title: Venminder OpenApi BusinessUnit ClientInformation API
  version: v1
security:
- Bearer: []
tags:
- name: ClientInformation
paths:
  /api/v1/ClientInformation/GetClientInformation:
    get:
      tags:
      - ClientInformation
      summary: Provides a list of basic vendor and product related information.
      description: Provides high level client configuration information including a list of the vendors and the vendor's products, a list of the profile fields for each vendor, a list of all active contracts and the products with which they are associated, a list of oversight requirements and a list of users.
      parameters:
      - name: createdDate
        in: query
        description: ''
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ClientInformation'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ClientInformation'
components:
  schemas:
    OpenApi.v1.User:
      title: OpenApi.v1.User
      type: object
      properties:
        key:
          type: string
          nullable: true
        isActive:
          type: boolean
        isEnrolled:
          type: boolean
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        emailAddress:
          type: string
          nullable: true
        fullName:
          type: string
          nullable: true
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.PhoneNumber'
          nullable: true
        createdByUserKeyOrDescription:
          type: string
          nullable: true
        createdDate:
          type: string
          format: date-time
          nullable: true
        roles:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.Role'
          nullable: true
      additionalProperties: false
      xml:
        name: User
    OpenApi.v1.Role:
      title: OpenApi.v1.Role
      type: object
      properties:
        key:
          type: string
          nullable: true
        roleName:
          type: string
          nullable: true
        isCustom:
          type: boolean
      additionalProperties: false
      xml:
        name: Role
    OpenApi.v1.PhoneNumber:
      title: OpenApi.v1.PhoneNumber
      type: object
      properties:
        type:
          type: string
          nullable: true
        areaCode:
          type: string
          nullable: true
        prefix:
          type: string
          nullable: true
        suffix:
          type: string
          nullable: true
        extension:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: PhoneNumber
    OpenApi.v1.ContractOverview:
      title: OpenApi.v1.ContractOverview
      type: object
      properties:
        key:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        isPerpetual:
          type: boolean
        effectiveDate:
          type: string
          format: date-time
          nullable: true
        notificationDeadline:
          type: string
          format: date-time
          nullable: true
        expirationDate:
          type: string
          format: date-time
          nullable: true
        vendorKey:
          type: string
          nullable: true
        productKeys:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
      xml:
        name: ContractOverview
    OpenApi.v1.ProductProfileDataField:
      title: OpenApi.v1.ProductProfileDataField
      type: object
      properties:
        key:
          type: string
          nullable: true
        label:
          type: string
          nullable: true
        answerFormat:
          type: string
          nullable: true
        parentKey:
          type: string
          nullable: true
        selectedParentOption:
          type: string
          nullable: true
        productsAppliedTo:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
      xml:
        name: ProductProfileDataField
    OpenApi.v1.Vendor:
      title: OpenApi.v1.Vendor
      type: object
      properties:
        key:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        isCritical:
          type: boolean
          nullable: true
        isThirdParty:
          type: boolean
        isFourthParty:
          type: boolean
        confidenceLevel:
          type: string
          nullable: true
        confidenceLevelComments:
          type: string
          nullable: true
        products:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.Product'
          nullable: true
        contracts:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.ContractOverview'
          nullable: true
        hasVendorSpendBudgets:
          type: boolean
        hasVendorSpendDetails:
          type: boolean
      additionalProperties: false
      xml:
        name: Vendor
    OpenApi.v1.OversightRequirement:
      title: OpenApi.v1.OversightRequirement
      type: object
      properties:
        key:
          type: string
          nullable: true
        label:
          type: string
          nullable: true
        appliesToAllProducts:
          type: boolean
      additionalProperties: false
      xml:
        name: OversightRequirement
    OpenApi.v1.BusinessUnit:
      title: OpenApi.v1.BusinessUnit
      type: object
      properties:
        key:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: BusinessUnit
    OpenApi.v1.Product:
      title: OpenApi.v1.Product
      type: object
      properties:
        key:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        isActive:
          type: boolean
        productType:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        createdDate:
          type: string
          format: date-time
      additionalProperties: false
      xml:
        name: Product
    OpenApi.v1.VendorProfileDataField:
      title: OpenApi.v1.VendorProfileDataField
      type: object
      properties:
        key:
          type: string
          nullable: true
        label:
          type: string
          nullable: true
        answerFormat:
          type: string
          nullable: true
        vendorsAppliedTo:
          type: array
          items:
            type: string
          nullable: true
        parentKey:
          type: string
          nullable: true
        selectedParentOption:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: VendorProfileDataField
    OpenApi.v1.RiskLevel:
      title: OpenApi.v1.RiskLevel
      type: object
      properties:
        key:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        score:
          type: integer
          format: int32
      additionalProperties: false
      xml:
        name: RiskLevel
    OpenApi.v1.ClientInformation:
      title: OpenApi.v1.ClientInformation
      type: object
      properties:
        vendors:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.Vendor'
          nullable: true
        vendorProfileDataFields:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.VendorProfileDataField'
          nullable: true
        productProfileDataFields:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.ProductProfileDataField'
          nullable: true
        oversightRequirements:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.OversightRequirement'
          nullable: true
        users:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.User'
          nullable: true
        businessUnits:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.BusinessUnit'
          nullable: true
        riskLevels:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.RiskLevel'
          nullable: true
        valueLists:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.ValueList'
          nullable: true
      additionalProperties: false
      xml:
        name: ClientInformation
    OpenApi.v1.ValueList:
      title: OpenApi.v1.ValueList
      type: object
      properties:
        key:
          type: string
          nullable: true
        label:
          type: string
          nullable: true
        dataKeyFieldLabel:
          type: string
          nullable: true
        dataKeyField:
          type: string
          nullable: true
        sortIndex:
          type: integer
          format: int32
      additionalProperties: false
      xml:
        name: ValueList
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
