openapi: 3.2.0
info:
  title: Venminder OpenApi Issues API
  version: v1
security:
- Bearer: []
tags:
- name: Issues
paths:
  /api/v1/Issues/GetAllIssues:
    get:
      tags:
      - Issues
      summary: Provides a list of all issues in the system
      description: Provides a basic high level set of information about all issues in the system. With this information you can drill down further for more details with other API calls.
      parameters:
      - name: cultureCode
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Issues.GetAllIssuesResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Issues.GetAllIssuesResponse'
      operationId: getApiV1IssuesGetAllIssues
      x-operation-id-source: derived
  /api/v1/Issues/GetIssueDetails:
    get:
      tags:
      - Issues
      summary: Provides details about a specific given issue
      description: Provides details about a specific given issue.
      parameters:
      - name: issueKey
        in: query
        schema:
          type: string
      - name: cultureCode
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Issues.IssueDetails'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Issues.IssueDetails'
      operationId: getApiV1IssuesGetIssueDetails
      x-operation-id-source: derived
components:
  schemas:
    OpenApi.v1.Issues.GetAllIssuesResponse:
      title: OpenApi.v1.Issues.GetAllIssuesResponse
      type: object
      properties:
        issues:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Issues.Issue'
      additionalProperties: false
      xml:
        name: Issues.GetAllIssuesResponse
    OpenApi.v1.Issues.Issue:
      title: OpenApi.v1.Issues.Issue
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        vendor:
          type:
          - string
          - 'null'
        vendorKey:
          type:
          - string
          - 'null'
        products:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Issues.IssueProduct'
        owner:
          type:
          - string
          - 'null'
        dateOpened:
          type: string
          format: date-time
        dateClosed:
          type:
          - string
          - 'null'
          format: date-time
        status:
          type:
          - string
          - 'null'
        severity:
          type:
          - string
          - 'null'
        severityKey:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Issues.Issue
    OpenApi.v1.Issues.IssueDetails:
      title: OpenApi.v1.Issues.IssueDetails
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        vendor:
          type:
          - string
          - 'null'
        vendorKey:
          type:
          - string
          - 'null'
        products:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Issues.IssueProduct'
        owner:
          type:
          - string
          - 'null'
        dateOpened:
          type: string
          format: date-time
        dateClosed:
          type:
          - string
          - 'null'
          format: date-time
        status:
          type:
          - string
          - 'null'
        originType:
          type:
          - string
          - 'null'
        originTypeKey:
          type:
          - string
          - 'null'
        originOfTheIssue:
          type:
          - string
          - 'null'
        severity:
          type:
          - string
          - 'null'
        severityKey:
          type:
          - string
          - 'null'
        issueApprovalRequired:
          type: boolean
        ownerAllowedToApprove:
          type: boolean
        comments:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Issues.IssueComment'
        additionalDetails:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Issues.IssueAdditionalDetails'
      additionalProperties: false
      xml:
        name: Issues.IssueDetails
    OpenApi.v1.Issues.IssueAdditionalDetails:
      title: OpenApi.v1.Issues.IssueAdditionalDetails
      type: object
      properties:
        questionKey:
          type:
          - string
          - 'null'
        question:
          type:
          - string
          - 'null'
        answerKey:
          type:
          - string
          - 'null'
        answer:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Issues.IssueAdditionalDetails
    OpenApi.v1.Issues.IssueComment:
      title: OpenApi.v1.Issues.IssueComment
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        commentor:
          type:
          - string
          - 'null'
        comment:
          type:
          - string
          - 'null'
        commentDate:
          type: string
          format: date-time
        documents:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Issues.IssueCommentDocument'
      additionalProperties: false
      xml:
        name: Issues.IssueComment
    OpenApi.v1.Issues.IssueCommentDocument:
      title: OpenApi.v1.Issues.IssueCommentDocument
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        fileName:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Issues.IssueCommentDocument
    OpenApi.v1.Issues.IssueProduct:
      title: OpenApi.v1.Issues.IssueProduct
      type: object
      properties:
        product:
          type:
          - string
          - 'null'
        key:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Issues.IssueProduct
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
