openapi: 3.2.0
info:
  title: Venminder OpenApi Oversight Task API
  version: v1
security:
- Bearer: []
tags:
- name: OversightTask
paths:
  /api/v1/OversightTask/GetOversightTask:
    get:
      tags:
      - OversightTask
      summary: Gets a specific Oversight Task by its key
      parameters:
      - name: key
        in: query
        description: This represents the key of the Oversight Task to be retrieved.
        schema:
          type: string
      - name: cultureCode
        in: header
        description: The culture code controls the language used in the response. Defaults to "en-US".
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightTask'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '401':
          description: Unauthorized
      operationId: getApiV1OversightTaskGetOversightTask
      x-operation-id-source: derived
  /api/v1/OversightTask/GetOversightTaskList:
    post:
      tags:
      - OversightTask
      summary: Get a list of all Oversight Tasks that fit the criteria provided in the request
      parameters:
      - name: cultureCode
        in: header
        description: The culture code controls the language used in the response. Defaults to "en-US".
        schema:
          type: string
      requestBody:
        description: The request object contains multiple properties allowing for the filtering of returned oversight task objects.
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
          application/*+xml:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.GetOversightTaskListRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightTask'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '401':
          description: Unauthorized
      operationId: postApiV1OversightTaskGetOversightTaskList
      x-operation-id-source: derived
  /api/v1/OversightTask/CreateOversightTask:
    post:
      tags:
      - OversightTask
      summary: Creates an Oversight Task with the provided properties and defaults from the…
      parameters:
      - name: cultureCode
        in: header
        description: The culture code controls the language used in the response. Defaults to "en-US".
        schema:
          type: string
      requestBody:
        description: The request object containing multiple properties that gets used during task creation.
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
          application/*+xml:
            schema:
              $ref: '#/components/schemas/OpenApi.v1.Oversight.Request.CreateOversightTaskRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '401':
          description: Unauthorized
      operationId: postApiV1OversightTaskCreateOversightTask
      x-operation-id-source: derived
  /api/v1/OversightTask/UpdateOversightTask/{key}:
    patch:
      tags:
      - OversightTask
      summary: Updates specific properties of an Oversight Task based on the provided PATCH…
      description: This PATCH endpoint only supports "replace", "add", and "remove" operations.
      parameters:
      - name: key
        in: path
        description: Provides the key of the Oversight Task that should be updated.
        required: true
        schema:
          type: string
      - name: cultureCode
        in: header
        description: The culture code controls the language used in the response. Defaults to "en-US".
        schema:
          type: string
      requestBody:
        description: A list of PATCH operations providing specific instructions on how to update the oversight task.
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OpenApi.v1.JsonPatch.Operations.Operation'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OpenApi.v1.JsonPatch.Operations.Operation'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OpenApi.v1.JsonPatch.Operations.Operation'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OpenApi.v1.JsonPatch.Operations.Operation'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '401':
          description: Unauthorized
      operationId: patchApiV1OversightTaskUpdateOversightTaskByKey
      x-operation-id-source: derived
components:
  schemas:
    OpenApi.v1.Oversight.OpenApiOversightTask:
      title: OpenApi.v1.Oversight.OpenApiOversightTask
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        requirementName:
          type:
          - string
          - 'null'
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        owner:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightTaskOwner'
        internalReviewer:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightContact'
        internalReviewerDate:
          type:
          - string
          - 'null'
          format: date-time
        externalReviewer:
          type:
          - string
          - 'null'
        externalReviewerDate:
          type:
          - string
          - 'null'
          format: date-time
        taskStatus:
          type:
          - string
          - 'null'
        approvalStatus:
          type:
          - string
          - 'null'
        vendorKey:
          type:
          - string
          - 'null'
        productKeys:
          type:
          - array
          - 'null'
          items:
            type: string
        lifecycle:
          type:
          - string
          - 'null'
        socType:
          type:
          - string
          - 'null'
        approver:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightContact'
        taskDocumentKeys:
          type:
          - array
          - 'null'
          items:
            type: string
        comments:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightTaskComment'
        reviewResult:
          type:
          - string
          - 'null'
        requirementKey:
          type:
          - string
          - 'null'
        completedDate:
          type:
          - string
          - 'null'
          format: date-time
        completedBy:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOversightContact'
        onboardingProperties:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOnboardingOversightTaskProperties'
        offboardingProperties:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOffboardingOversightTaskProperties'
      additionalProperties: false
      xml:
        name: Oversight.OpenApiOversightTask
    OpenApi.v1.ErrorResource:
      title: OpenApi.v1.ErrorResource
      type: object
      properties:
        resourceKey:
          type:
          - string
          - 'null'
        resourceValue:
          type:
          - string
          - 'null'
        field:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: ErrorResource
    OpenApi.v1.Oversight.Request.CreateOversightTaskRequest:
      title: OpenApi.v1.Oversight.Request.CreateOversightTaskRequest
      type: object
      properties:
        oversightRequirementKey:
          type:
          - string
          - 'null'
        ownerKey:
          type:
          - string
          - 'null'
        ownerType:
          type:
          - string
          - 'null'
        startDate:
          type: string
          format: date-time
        productsKeys:
          type:
          - array
          - 'null'
          items:
            type: string
        vendorKey:
          type:
          - string
          - 'null'
        onboardingProperties:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOnboardingOversightTaskProperties'
        offboardingProperties:
          $ref: '#/components/schemas/OpenApi.v1.Oversight.OpenApiOffboardingOversightTaskProperties'
      additionalProperties: false
      xml:
        name: Oversight.Request.CreateOversightTaskRequest
    OpenApi.v1.Oversight.OpenApiOversightContact:
      title: OpenApi.v1.Oversight.OpenApiOversightContact
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Oversight.OpenApiOversightContact
    OpenApi.v1.ErrorResponse:
      title: OpenApi.v1.ErrorResponse
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.ErrorResource'
      additionalProperties: false
      xml:
        name: ErrorResponse
    OpenApi.v1.Oversight.OpenApiOnboardingOversightTaskProperties:
      title: OpenApi.v1.Oversight.OpenApiOnboardingOversightTaskProperties
      type: object
      properties:
        requestRelationshipKey:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Oversight.OpenApiOnboardingOversightTaskProperties
    OpenApi.v1.Oversight.OpenApiOversightTaskOwner:
      title: OpenApi.v1.Oversight.OpenApiOversightTaskOwner
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Oversight.OpenApiOversightTaskOwner
    OpenApi.v1.Oversight.OpenApiOffboardingOversightTaskProperties:
      title: OpenApi.v1.Oversight.OpenApiOffboardingOversightTaskProperties
      type: object
      properties:
        requestKey:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Oversight.OpenApiOffboardingOversightTaskProperties
    OpenApi.v1.Oversight.Request.GetOversightTaskListRequest:
      title: OpenApi.v1.Oversight.Request.GetOversightTaskListRequest
      type: object
      properties:
        keys:
          type:
          - array
          - 'null'
          items:
            type: string
        statuses:
          type:
          - array
          - 'null'
          items:
            type: string
        lifecycles:
          type:
          - array
          - 'null'
          items:
            type: string
        vendorKeys:
          type:
          - array
          - 'null'
          items:
            type: string
        productKeys:
          type:
          - array
          - 'null'
          items:
            type: string
        startDate:
          type:
          - string
          - 'null'
          format: date-time
        endDate:
          type:
          - string
          - 'null'
          format: date-time
        reviewResults:
          type:
          - array
          - 'null'
          items:
            type: string
        taskOwnerKeys:
          type:
          - array
          - 'null'
          items:
            type: string
        requirementKeys:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
      xml:
        name: Oversight.Request.GetOversightTaskListRequest
    OpenApi.v1.JsonPatch.Operations.Operation:
      title: OpenApi.v1.JsonPatch.Operations.Operation
      type: object
      properties:
        path:
          type:
          - string
          - 'null'
        op:
          type:
          - string
          - 'null'
        from:
          type:
          - string
          - 'null'
        value: {}
      additionalProperties: false
      xml:
        name: JsonPatch.Operations.Operation
    OpenApi.v1.Oversight.OpenApiOversightTaskComment:
      title: OpenApi.v1.Oversight.OpenApiOversightTaskComment
      type: object
      properties:
        commentString:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Oversight.OpenApiOversightTaskComment
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
