openapi: 3.0.1
info:
  title: Venminder OpenApi BusinessUnit Contact API
  version: v1
security:
- Bearer: []
tags:
- name: Contact
paths:
  /api/v1/Contact/GetContactList:
    get:
      tags:
      - Contact
      summary: Provides a list of internal and external contacts.
      description: Provides a list of internal and external contacts. This includes name, email address, phone numbers, if contact is enrolled and active, and vendors and products the external contact is assigned to.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ContactListResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ContactListResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
components:
  schemas:
    OpenApi.v1.PhoneNumber:
      title: OpenApi.v1.PhoneNumber
      type: object
      properties:
        type:
          type: string
          nullable: true
        areaCode:
          type: string
          nullable: true
        prefix:
          type: string
          nullable: true
        suffix:
          type: string
          nullable: true
        extension:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: PhoneNumber
    OpenApi.v1.Role:
      title: OpenApi.v1.Role
      type: object
      properties:
        key:
          type: string
          nullable: true
        roleName:
          type: string
          nullable: true
        isCustom:
          type: boolean
      additionalProperties: false
      xml:
        name: Role
    OpenApi.v1.InternalContact:
      title: OpenApi.v1.InternalContact
      type: object
      properties:
        key:
          type: string
          nullable: true
        isActive:
          type: boolean
        isEnrolled:
          type: boolean
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        emailAddress:
          type: string
          nullable: true
        fullName:
          type: string
          nullable: true
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.PhoneNumber'
          nullable: true
        createdByUserKeyOrDescription:
          type: string
          nullable: true
        createdDate:
          type: string
          format: date-time
          nullable: true
        roles:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.Role'
          nullable: true
      additionalProperties: false
      xml:
        name: InternalContact
    OpenApi.v1.ContactListResponse:
      title: OpenApi.v1.ContactListResponse
      type: object
      properties:
        internalContacts:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.InternalContact'
          nullable: true
        externalContacts:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.ExternalContact'
          nullable: true
      additionalProperties: false
      xml:
        name: ContactListResponse
    OpenApi.v1.ErrorResponse:
      title: OpenApi.v1.ErrorResponse
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        errors:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.ErrorResource'
          nullable: true
      additionalProperties: false
      xml:
        name: ErrorResponse
    OpenApi.v1.ErrorResource:
      title: OpenApi.v1.ErrorResource
      type: object
      properties:
        resourceKey:
          type: string
          nullable: true
        resourceValue:
          type: string
          nullable: true
        field:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: ErrorResource
    OpenApi.v1.ExternalContact:
      title: OpenApi.v1.ExternalContact
      type: object
      properties:
        addressBookKey:
          type: string
          nullable: true
        contactKey:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        fullName:
          type: string
          nullable: true
        emailAddress:
          type: string
          nullable: true
        isEnrolled:
          type: boolean
        isActive:
          type: boolean
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.PhoneNumber'
          nullable: true
        vendorsAppliedTo:
          type: array
          items:
            type: string
          nullable: true
        productsAppliedTo:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
      xml:
        name: ExternalContact
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
