openapi: 3.0.1
info:
  title: Venminder OpenApi BusinessUnit Venmonitor API
  version: v1
security:
- Bearer: []
tags:
- name: Venmonitor
paths:
  /api/v1/Venmonitor/GetVendorScore:
    get:
      tags:
      - Venmonitor
      parameters:
      - name: vendorKey
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenApi.v1.Venmonitor.GetVendorScoreResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Venmonitor.GetVendorScoreResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
components:
  schemas:
    OpenApi.v1.Venmonitor.GetVendorScoreResponse:
      title: OpenApi.v1.Venmonitor.GetVendorScoreResponse
      type: object
      properties:
        vendorNickname:
          type: string
          nullable: true
        vendorKey:
          type: string
          nullable: true
        venmonitorType:
          type: string
          nullable: true
        publishedDate:
          type: string
          format: date-time
          nullable: true
        lastRefreshDate:
          type: string
          format: date-time
          nullable: true
        overallScoreQuantitative:
          type: number
          format: double
          nullable: true
        overallScoreQualitative:
          type: string
          nullable: true
        dataPartnerScores:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.Venmonitor.DataPartnerScore'
          nullable: true
      additionalProperties: false
      xml:
        name: Venmonitor.GetVendorScoreResponse
    OpenApi.v1.ErrorResource:
      title: OpenApi.v1.ErrorResource
      type: object
      properties:
        resourceKey:
          type: string
          nullable: true
        resourceValue:
          type: string
          nullable: true
        field:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: ErrorResource
    OpenApi.v1.Venmonitor.DataPartnerScore:
      title: OpenApi.v1.Venmonitor.DataPartnerScore
      type: object
      properties:
        dataPartnerName:
          type: string
          nullable: true
        normalizedScoreQuantitative:
          type: number
          format: double
          nullable: true
        normalizedScoreQualitative:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: Venmonitor.DataPartnerScore
    OpenApi.v1.ErrorResponse:
      title: OpenApi.v1.ErrorResponse
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        errors:
          type: array
          items:
            $ref: '#/components/schemas/OpenApi.v1.ErrorResource'
          nullable: true
      additionalProperties: false
      xml:
        name: ErrorResponse
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
