openapi: 3.2.0
info:
  title: Venminder OpenApi Contact API
  version: v1
security:
- Bearer: []
tags:
- name: Contact
paths:
  /api/v1/Contact/GetContactList:
    get:
      tags:
      - Contact
      summary: Provides a list of internal and external contacts
      description: Provides a list of internal and external contacts. This includes name, email address, phone numbers, if contact is enrolled and active, and vendors and products the external contact is assigned to.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ContactListResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ContactListResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
      operationId: getApiV1ContactGetContactList
      x-operation-id-source: derived
components:
  schemas:
    OpenApi.v1.ErrorResource:
      title: OpenApi.v1.ErrorResource
      type: object
      properties:
        resourceKey:
          type:
          - string
          - 'null'
        resourceValue:
          type:
          - string
          - 'null'
        field:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: ErrorResource
    OpenApi.v1.ContactListResponse:
      title: OpenApi.v1.ContactListResponse
      type: object
      properties:
        internalContacts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.InternalContact'
        externalContacts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.ExternalContact'
      additionalProperties: false
      xml:
        name: ContactListResponse
    OpenApi.v1.ErrorResponse:
      title: OpenApi.v1.ErrorResponse
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.ErrorResource'
      additionalProperties: false
      xml:
        name: ErrorResponse
    OpenApi.v1.ExternalContact:
      title: OpenApi.v1.ExternalContact
      type: object
      properties:
        addressBookKey:
          type:
          - string
          - 'null'
        contactKey:
          type:
          - string
          - 'null'
        firstName:
          type:
          - string
          - 'null'
        lastName:
          type:
          - string
          - 'null'
        fullName:
          type:
          - string
          - 'null'
        emailAddress:
          type:
          - string
          - 'null'
        isEnrolled:
          type: boolean
        isActive:
          type: boolean
        phoneNumbers:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.PhoneNumber'
        vendorsAppliedTo:
          type:
          - array
          - 'null'
          items:
            type: string
        productsAppliedTo:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
      xml:
        name: ExternalContact
    OpenApi.v1.Role:
      title: OpenApi.v1.Role
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        roleName:
          type:
          - string
          - 'null'
        isCustom:
          type: boolean
      additionalProperties: false
      xml:
        name: Role
    OpenApi.v1.PhoneNumber:
      title: OpenApi.v1.PhoneNumber
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        areaCode:
          type:
          - string
          - 'null'
        prefix:
          type:
          - string
          - 'null'
        suffix:
          type:
          - string
          - 'null'
        extension:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: PhoneNumber
    OpenApi.v1.InternalContact:
      title: OpenApi.v1.InternalContact
      type: object
      properties:
        key:
          type:
          - string
          - 'null'
        isActive:
          type: boolean
        isEnrolled:
          type: boolean
        firstName:
          type:
          - string
          - 'null'
        lastName:
          type:
          - string
          - 'null'
        emailAddress:
          type:
          - string
          - 'null'
        fullName:
          type:
          - string
          - 'null'
        phoneNumbers:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.PhoneNumber'
        createdByUserKeyOrDescription:
          type:
          - string
          - 'null'
        createdDate:
          type:
          - string
          - 'null'
          format: date-time
        roles:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Role'
      additionalProperties: false
      xml:
        name: InternalContact
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
