openapi: 3.2.0
info:
  title: Venminder OpenApi Venmonitor API
  version: v1
security:
- Bearer: []
tags:
- name: Venmonitor
paths:
  /api/v1/Venmonitor/GetVendorScore:
    get:
      tags:
      - Venmonitor
      parameters:
      - name: vendorKey
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenApi.v1.Venmonitor.GetVendorScoreResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.Venmonitor.GetVendorScoreResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OpenApi.v1.ErrorResponse'
      summary: Get api venmonitor get vendor score
      x-summary-source: derived
      operationId: getApiV1VenmonitorGetVendorScore
      x-operation-id-source: derived
components:
  schemas:
    OpenApi.v1.Venmonitor.DataPartnerScore:
      title: OpenApi.v1.Venmonitor.DataPartnerScore
      type: object
      properties:
        dataPartnerName:
          type:
          - string
          - 'null'
        normalizedScoreQuantitative:
          type:
          - number
          - 'null'
          format: double
        normalizedScoreQualitative:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: Venmonitor.DataPartnerScore
    OpenApi.v1.Venmonitor.GetVendorScoreResponse:
      title: OpenApi.v1.Venmonitor.GetVendorScoreResponse
      type: object
      properties:
        vendorNickname:
          type:
          - string
          - 'null'
        vendorKey:
          type:
          - string
          - 'null'
        venmonitorType:
          type:
          - string
          - 'null'
        publishedDate:
          type:
          - string
          - 'null'
          format: date-time
        lastRefreshDate:
          type:
          - string
          - 'null'
          format: date-time
        overallScoreQuantitative:
          type:
          - number
          - 'null'
          format: double
        overallScoreQualitative:
          type:
          - string
          - 'null'
        dataPartnerScores:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.Venmonitor.DataPartnerScore'
      additionalProperties: false
      xml:
        name: Venmonitor.GetVendorScoreResponse
    OpenApi.v1.ErrorResponse:
      title: OpenApi.v1.ErrorResponse
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/OpenApi.v1.ErrorResource'
      additionalProperties: false
      xml:
        name: ErrorResponse
    OpenApi.v1.ErrorResource:
      title: OpenApi.v1.ErrorResource
      type: object
      properties:
        resourceKey:
          type:
          - string
          - 'null'
        resourceValue:
          type:
          - string
          - 'null'
        field:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: ErrorResource
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please insert access token with Bearer into field eg. Bearer eyJhbGciOiJSUzI1Ni and click authorize.
      name: Authorization
      in: header
